#!/usr/bin/env zsh
#
# Copyright (c) 2016-2021 Sebastian Gniazdowski and contributors
# Copyright (c) 2021-2022 zdharma-continuum and contributors

# vim: set expandtab filetype=zsh shiftwidth=2 softtabstop=2 tabstop=2:
