#!/usr/bin/env zsh
#
# Copyright (c) 2016-2020 Sebastian Gniazdowski and contributors
# Copyright (c) 2021-2022 zdharma-continuum and contributors

print -- " \
  Its syntax is:
  ${ZINIT[col-info2]}submods'${ZINIT[col-uname]}{user}${ZINIT[col-rst]}/ \
  ${ZINIT[col-pname]}{plugin}${ZINIT[col-info2]} –> \
  ${ZINIT[col-p]}{output-dir}${ZINIT[col-rst]}${ZINIT[col-info2]}; ...'${ZINIT[col-rst]}"

print -- " \
  It will clone the ${ZINIT[col-uname]}{user}${ZINIT[col-rst]}/ ${ZINIT[col-pname]}{plugin}${ZINIT[col-rst]} from GitHub into \
  ${ZINIT[col-p]}{output-dir}${ZINIT[col-rst]} inside the containing plugin or snippet. \
  The submodule will be correctly updated on ${ZINIT[col-info2]}\`zinit update ...'${ZINIT[col-rst]}"
