#!/usr/bin/env zsh
#
# -*- mode: sh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim:ft=zsh:sw=2:sts=2:et:
#
# Copyright (c) 2016-2021 Sebastian Gniazdowski and contributors
# Copyright (c) 2021-2022 zdharma-continuum and contributors
#

print -- "\nThe ice ${ZINIT[col-info2]}submods''${ZINIT[col-rst]} is currently" "being registered by the ${ZINIT[col-pname]}zinit-annex-submods${ZINIT[col-rst]} z-plugin"
print -- "Its syntax is:" "${ZINIT[col-info2]}submods'${ZINIT[col-uname]}{user}${ZINIT[col-rst]}/""${ZINIT[col-pname]}{plugin}${ZINIT[col-info2]} –>" "${ZINIT[col-p]}{output-dir}${ZINIT[col-rst]}${ZINIT[col-info2]}; ...'${ZINIT[col-rst]}"
print -- "It will clone the ${ZINIT[col-uname]}{user}${ZINIT[col-rst]}/""${ZINIT[col-pname]}{plugin}${ZINIT[col-rst]} from GitHub into the" "${ZINIT[col-p]}{output-dir}${ZINIT[col-rst]}" "inside the containing plugin or snippet." "The submodule will be correctly updated on" "${ZINIT[col-info2]}\`zinit update ...'${ZINIT[col-rst]}"
